name = "cf-location-lookup"
main = "src/index.js"
compatibility_date = "2024-08-06"
compatibility_flags = ["nodejs_compat"]

# Allow external requests for fallback geolocation
[env.production]
name = "cf-location-lookup"

[env.staging]
name = "cf-location-lookup-staging"

routes = [
  { pattern = "loclook.iwpi.com", custom_domain = true }
]